
###########################################
# Mongo DB Configuration
###########################################

test:
   dbhost: localhost
   dbport: 27017
   dbname: testdb
   migrations_collection: migrations
   profiles_collection: profiles

development:
   dbhost: localhost
   dbport: 27017
   dbname: developmentdb
   migrations_collection: migrations
   profiles_collection: profiles

production:
   dbhost: ip-172-31-5-119.ec2.internal
   dbport: 27017
   dbname: productiondb
   migrations_collection: migrations
   profiles_collection: profiles